# NumPy Indexing and Selection Notes

In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
slice_of_arr = arr[0:6]

In [7]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
slice_of_arr[:] =99  # Broadcasting, and changing all values to assigned number. Original array arr will also be changed

In [10]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
# COPYING AN ARRRAY
# IF YOU MAKE A CHANGE IN THE COPIED ARRAY, IT WON'T AFFECT THE ORIGINAL COPY UNLIKE IF YOU SLICE AN ARRAY AND THEN USE BROADCAST VALUES
arr_copy = arr.copy()

In [13]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing 2D Array

In [19]:
arr_2D = np.array([[5,10,15], [20,25,30], [35, 40, 45]])

In [20]:
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
# Double bracket format to retrieve values in a 2D array
arr_2D[0][0]

5

In [23]:
# Single bracket format to retrieve values in a 2D array, RECOMMENDED
arr_2D[2,1]

40

In [24]:
# TO GRAB CERTAIN SECTIONS OF AN ARRAY
arr_2D[:2, 1:]

array([[10, 15],
       [25, 30]])